qa_database = {
    "what is your name": "I am your voice assistant.",
    "who Is Rabbi": "Mr Rabbi, his full name is Md Mehedi Hassan, a developer of Triumph Digital.",
    "how are you": "I'm doing well, thank you!",
    "Did you hear about the new celebrity couple?": "Yes, they've been all over the news lately!",
    "What do you think of the latest fashion trends?": "I love how daring they are this season!",
    "Have you watched the latest blockbuster movie?": "It was amazing! The special effects were mind-blowing.",
    "Did you see who got eliminated from that reality TV show?": "Yes, I was so surprised! I thought they would make it to the end.",
    "Have you heard about the scandal involving that politician?": "Yes, it's been all over social media. It's hard to keep up with all the drama!",
    "What's your opinion on the new restaurant in town?": "I haven't tried it yet, but I've heard mixed reviews.",
    "Did you see that viral video everyone's talking about?": "Yes, it was hilarious! I couldn't stop laughing.",
    "Have you read the latest best-selling novel?": "No, but it's on my list of books to read. I've heard great things about it.",
    "Did you hear about the drama at work?": "Yes, it's been quite the topic of conversation in the office.",
    "What's your take on the latest celebrity scandal?": "I think it's just another example of how fame can change people.",
    "Did you catch the finale of that TV series?": "Yes, it was so emotional! I'm sad it's over.",
    "Have you seen the latest gossip magazine?": "No, but I heard it's filled with juicy stories.",
    "What's your opinion on that controversial social media post?": "I think it's important to consider all perspectives before jumping to conclusions.",
    "Did you hear about the surprise wedding?": "Yes, it was such a romantic gesture!",
    "Have you tried the new coffee shop downtown?": "Not yet, but I've heard they have the best pastries.",
    "Did you see that shocking plot twist in the TV series?": "Yes, it completely caught me off guard!",
    "What's your reaction to the latest celebrity breakup?": "I'm not surprised. It seems like celebrity relationships never last.",
    "Did you hear about the scandalous affair?": "Yes, it's been the talk of the town.",
    "Have you seen the latest episode of the reality show?": "No, but I heard it was full of drama.",
    "What's your opinion on the new album from that artist?": "I think it's their best work yet!",
    "Did you see the paparazzi photos of that celebrity?": "Yes, they were everywhere!",
    "Have you heard about the upcoming awards ceremony?": "Yes, I can't wait to see who wins!",
    "What do you think of the latest gossip spreading around?": "I try not to pay too much attention to gossip, but it's hard to avoid sometimes.",
    "Did you catch the interview with the famous actor?": "No, but I heard they revealed some interesting secrets.",
    "Have you seen the latest red carpet fashion?": "Yes, it was stunning! Everyone looked amazing.",
    "What's your reaction to the scandalous revelations?": "I'm shocked! I never would have guessed.",
    "Did you hear about the surprise engagement?": "Yes, it was so romantic!",
    "Have you tried the new restaurant everyone's talking about?": "Not yet, but I've heard it's delicious.",
    "What's your take on the latest celebrity feud?": "I think it's just for publicity.",
    "Did you see the viral video that's been trending?": "Yes, it was hilarious! I couldn't stop watching.",
    "Have you read the latest gossip column?": "No, but I heard it's full of juicy details.",
    "What's your opinion on the controversial tweet?": "I think it was taken out of context.",
    "Did you hear about the shocking revelation?": "Yes, I can't believe it!",
    "Have you watched the latest episode of the TV series?": "Yes, it was intense!",
    "What's your reaction to the unexpected plot twist?": "I didn't see it coming!",
    "Did you hear about the scandalous rumor?": "Yes, it's been causing quite a stir.",
    "Have you seen the latest gossip magazine cover?": "No, but I heard it's scandalous.",
    "What's your take on the recent controversy?": "I think there are always two sides to every story.",
    "Did you catch the interview with the famous singer?": "No, but I heard they dropped some major news.",
    "Have you seen the latest fashion trend?": "Yes, I love how bold it is!",
    "What's your opinion on the recent celebrity sighting?": "I think it's cool that they're out and about like everyone else.",
    "Did you hear about the surprise announcement?": "Yes, it came out of nowhere!",
    "Have you tried the new dessert at that bakery?": "Not yet, but I've heard it's delicious.",
    "What's your reaction to the shocking revelation?": "I'm speechless!",
    "Did you see the latest episode of the reality TV show?": "Yes, it was full of drama as usual.",
    "What's your take on the recent scandal?": "I think it's blown out of proportion.",
    "Did you hear about the scandalous affair?": "Yes, it's been the talk of the town.",
    "Have you seen the latest viral video?": "No, but I heard it's hilarious.",
    "What's your opinion on the controversial social media post?": "I think people are overreacting.",
    "Did you catch the interview with the famous actor?": "No, but I heard it was revealing.",
    "Have you read the latest gossip magazine?": "No, but I heard it's full of juicy gossip.",
    "What's your reaction to the latest celebrity breakup?": "I'm not surprised. It seems like they were never meant to last.",
    "Did you hear about the surprise wedding?": "Yes, it was so romantic!",
    "Have you tried the new coffee shop downtown?": "Not yet, but I've heard it's amazing.",
    "What's your take on the latest plot twist in the TV series?": "I didn't see it coming at all!",
    "Did you see the shocking paparazzi photos?": "Yes, they were everywhere!",
    "Have you heard about the upcoming movie premiere?": "Yes, I can't wait to see it!",
    "What do you think of the latest gossip circulating around?": "I try not to pay too much attention to gossip, but it's hard to avoid sometimes.",
    "Did you catch the interview with the famous actress?": "No, but I heard it was controversial.",
    "Have you seen the latest fashion trend?": "Yes, I love how bold it is!",
    "What's your opinion on the recent scandal?": "I think people are blowing it out of proportion.",
    "Did you hear about the surprise engagement?": "Yes, it was so unexpected!",
    "Have you tried the new restaurant everyone's raving about?": "Not yet, but I've heard it's amazing.",
    "What's your take on the recent celebrity feud?": "I think it's just for publicity.",
    "Did you see the viral video everyone's talking about?": "Yes, it was hilarious!",
    "Have you read the latest gossip column?": "No, but I heard it's full of juicy details.",
    "What's your reaction to the shocking revelation?": "I'm speechless!",
    "Did you hear about the surprise announcement?": "Yes, it caught everyone off guard!",
    "Have you tried the new dessert at that bakery?": "Not yet, but I've heard it's to die for.",
    "What's your take on the recent controversy?": "I think there's more to the story than meets the eye.",
    "Did you catch the interview with the famous singer?": "No, but I heard it was explosive.",
    "Have you seen the latest fashion trend?": "Yes, it's so unique!",
    "What's your opinion on the recent celebrity sighting?": "I think it's cool that they're out and about like everyone else.",
    "Did you hear about the surprise party?": "Yes, it was such a fun night!",
    "Have you tried the new cocktail at that bar?": "Not yet, but I've heard it's delicious.",
    "What's your reaction to the unexpected turn of events?": "I didn't see that coming at all!",
    "Did you see the latest episode of the reality TV show?": "Yes, it was full of drama as usual.",
    "What's your take on the recent scandal?": "I think people are blowing it out of proportion.",
    "Did you hear about the scandalous affair?": "Yes, it's been the talk of the town.",
    "Have you seen the latest viral video?": "No, but I heard it's hilarious.",
    "What's your opinion on the controversial social media post?": "I think people are overreacting.",
    "Did you catch the interview with the famous actor?": "No, but I heard it was revealing.",
    "Have you read the latest gossip magazine?": "No, but I heard it's full of juicy gossip.",
    "What's your reaction to the latest celebrity breakup?": "I'm not surprised. It seems like they were never meant to last.",
    "Did you hear about the surprise wedding?": "Yes, it was so romantic!",
    "Have you tried the new coffee shop downtown?": "Not yet, but I've heard it's amazing.",
    "What's your take on the latest plot twist in the TV series?": "I didn't see it coming at all!",
    "Did you see the shocking paparazzi photos?": "Yes, they were everywhere!",
    "Have you heard about the upcoming movie premiere?": "Yes, I can't wait to see it!",
    "What do you think of the latest gossip circulating around?": "I try not to pay too much attention to gossip, but it's hard to avoid sometimes.",
    "Did you catch the interview with the famous actress?": "No, but I heard it was controversial.",
    "Have you seen the latest fashion trend?": "Yes, I love how bold it is!",
    "What's your opinion on the recent scandal?": "I think people are blowing it out of proportion.",
    "Did you hear about the surprise engagement?": "Yes, it was so unexpected!",
    "Have you tried the new restaurant everyone's raving about?": "Not yet, but I've heard it's amazing.",
    "What's your take on the recent celebrity feud?": "I think it's just for publicity.",
    "Did you see the viral video everyone's talking about?": "Yes, it was hilarious!",
    "Have you read the latest gossip column?": "No, but I heard it's full of juicy details.",
    "What's your reaction to the shocking revelation?": "I'm speechless!",
    "Did you hear about the surprise announcement?": "Yes, it caught everyone off guard!",
    "Have you tried the new dessert at that bakery?": "Not yet, but I've heard it's to die for.",
    "What's your take on the recent controversy?": "I think there's more to the story than meets the eye.",
    "Did you catch the interview with the famous singer?": "No, but I heard it was explosive.",
    "Have you seen the latest fashion trend?": "Yes, it's so unique!",
    "What's your opinion on the recent celebrity sighting?": "I think it's cool that they're out and about like everyone else.",
    "Did you hear about the surprise party?": "Yes, it was such a fun night!",
    "Have you tried the new cocktail at that bar?": "Not yet, but I've heard it's delicious.",
    "What's your reaction to the unexpected turn of events?": "I didn't see that coming at all!",
    "Did you see the latest episode of the reality TV show?": "Yes, it was full of drama as usual.",
    "What's your take on the recent scandal?": "I think people are blowing it out of proportion.",
    "Did you hear about the scandalous affair?": "Yes, it's been the talk of the town.",
    "Have you seen the latest viral video?": "No, but I heard it's hilarious.",
    "What's your opinion on the controversial social media post?": "I think people are overreacting.",
    "Did you catch the interview with the famous actor?": "No, but I heard it was revealing.",
    "Have you read the latest gossip magazine?": "No, but I heard it's full of juicy gossip.",
    "What's your reaction to the latest celebrity breakup?": "I'm not surprised. It seems like they were never meant to last.",
}
